[build-system]
requires = [
  "wheel",
  "scikit-build",
  "cmake",
  "Cython",
  "ninja; platform_system!='Windows'"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = ["*-musllinux_*", "*cp36*", "*cp37*"]
archs = "auto64"
build-verbosity = 3

[tool.cibuildwheel.environment]
NEST_CMAKE_BUILDWHEEL="ON"
NEST_INSTALL_NODOC=true
CMAKE_ARGS="-DCMAKE_MODULE_PATH=/project/cmake"
BOOST_ROOT="/boost"
GSL_ROOT_DIR="/gsl"

[tool.cibuildwheel.linux]
before-build = "python3 extras/wheelbuild/prepare_container.py"
